
# ░░░░░░░░░░░░░░░░░░░█████╗░██╗░░░░░░█████╗░░█████╗░██████╗░██╗████████╗████████╗██╗░░░██╗░░░░░░░░░░░░░░░░░░
# ░░░░░░░░░░░░░░░░░░██╔══██╗██║░░░░░██╔══██╗██╔══██╗██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗░██╔╝░░░░░░░░░░░░░░░░░░
# █████╗█████╗█████╗███████║██║░░░░░███████║██║░░╚═╝██████╔╝██║░░░██║░░░░░░██║░░░░╚████╔╝░█████╗█████╗█████╗
# ╚════╝╚════╝╚════╝██╔══██║██║░░░░░██╔══██║██║░░██╗██╔══██╗██║░░░██║░░░░░░██║░░░░░╚██╔╝░░╚════╝╚════╝╚════╝
# ░░░░░░░░░░░░░░░░░░██║░░██║███████╗██║░░██║╚█████╔╝██║░░██║██║░░░██║░░░░░░██║░░░░░░██║░░░░░░░░░░░░░░░░░░░░░
# ░░░░░░░░░░░░░░░░░░╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝░╚════╝░╚═╝░░╚═╝╚═╝░░░╚═╝░░░░░░╚═╝░░░░░░╚═╝░░░░░░░░░░░░░░░░░░░░░



import = ["~/.config/alacritty/colors.toml", "~/.config/alacritty/fonts.toml"]

[cursor]
blink_interval = 500
unfocused_hollow = true
thickness = 0.1

[cursor.style]
blinking = "on"
shape = "Beam"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "none"
dynamic_title = true
opacity = 0.9
dynamic_padding = true


[window.padding]
x = 15
y = 15

[scrolling]
history = 10000
multiplier = 3


[general]
live_config_reload = true

