
# ░░░░░░░░░░░░░░░░░░░█████╗░░█████╗░██╗░░░░░░█████╗░██████╗░░██████╗░░░░░░░░░░░░░░░░░░
# ░░░░░░░░░░░░░░░░░░██╔══██╗██╔══██╗██║░░░░░██╔══██╗██╔══██╗██╔════╝░░░░░░░░░░░░░░░░░░
# █████╗█████╗█████╗██║░░╚═╝██║░░██║██║░░░░░██║░░██║██████╔╝╚█████╗░█████╗█████╗█████╗
# ╚════╝╚════╝╚════╝██║░░██╗██║░░██║██║░░░░░██║░░██║██╔══██╗░╚═══██╗╚════╝╚════╝╚════╝
# ░░░░░░░░░░░░░░░░░░╚█████╔╝╚█████╔╝███████╗╚█████╔╝██║░░██║██████╔╝░░░░░░░░░░░░░░░░░░
# ░░░░░░░░░░░░░░░░░░░╚════╝░░╚════╝░╚══════╝░╚════╝░╚═╝░░╚═╝╚═════╝░░░░░░░░░░░░░░░░░░░

# Default colors
[colors.primary]
background = "#000000"
foreground = "#f50057"

# Cursor colors
[colors.cursor]
cursor = "#00ff00"
text = "#ff4081"

# Normal colors
[colors.normal]
black = "#000000"
red = "#ff0000"
green = "#00ff28"
yellow = "#ffff00"
blue = "#0fffff"
magenta = "#db0077"
cyan = "#2196f3"
white = "#c501e2"

